apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: intent-classification-engine
  title: Intent Classification Engine
  description: Core microservice that classifies user intent from text input using ML models
spec:
  type: service
  lifecycle: production
  owner: user:Amit
  providesApis:
    - intent-api
  consumesApis:
    - nlp-api
  partOf:
    - ai-core-system
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: response-generator-service
  title: Response Generator Service
  description: Generates dynamic and personalized responses using intent and context data
spec:
  type: service
  lifecycle: production
  owner: user:Amit
  providesApis:
    - response-api
  consumesApis:
    - context-api
    - intent-api
  partOf:
    - ai-core-system
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: feedback-loop-analyzer
  title: Feedback Loop Analyzer
  description: Analyzes user feedback to improve response accuracy and user satisfaction
spec:
  type: service
  lifecycle: production
  owner: user:Amit
  providesApis:
    - feedback-api
  consumesApis:
    - response-api
  partOf:
    - analytics-optimization-system
