apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: event-streaming-service
  title: Event Streaming Service
  description: Collects and streams user interaction events from the chatbot in real-time
spec:
  type: service
  lifecycle: production
  owner: user:Amninder
  providesApis:
    - event-stream-api
  partOf:
    - data-observability-system
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: analytics-data-warehouse
  title: Analytics Data Warehouse
  description: Stores long-term chatbot usage data for advanced querying and reporting
spec:
  type: service
  lifecycle: production
  owner: user:Amninder
  providesApis:
    - warehouse-api
  consumesApis:
    - event-stream-api
  partOf:
    - data-observability-system
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: session-heatmap-service
  title: Session Heatmap Service
  description: Provides visual session activity heatmaps to support traffic analysis and load balancing
spec:
  type: service
  lifecycle: production
  owner: user:Amninder
  providesApis:
    - heatmap-api
  consumesApis:
    - warehouse-api
  partOf:
    - chatbot-optimization-system
