apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: model-inference-engine
  title: Model Inference Engine
  description: Core service for executing AI model inference requests for the chatbot
spec:
  type: service
  lifecycle: production
  owner: user:Harpreet
  providesApis:
    - inference-api
  partOf:
    - model-execution-system
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: response-logger-service
  title: Response Logger Service
  description: Logs AI-generated chatbot responses for auditing and training analysis
spec:
  type: service
  lifecycle: production
  owner: user:Harpreet
  providesApis:
    - logger-api
  consumesApis:
    - inference-api
  partOf:
    - feedback-learning-system
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sentiment-analysis-service
  title: Sentiment Analysis Service
  description: Scores user messages for sentiment to guide chatbot response tone
spec:
  type: service
  lifecycle: production
  owner: user:Harpreet
  providesApis:
    - sentiment-api
  partOf:
    - model-execution-system
