apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: chatbot-training-service
  title: Chatbot Training Service
  description: Trains the chatbot using new conversation datasets and improves AI responses
spec:
  type: service
  lifecycle: production
  owner: user:Parv
  providesApis:
    - training-api
  partOf:
    - ai-optimization-system
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: response-optimization-service
  title: Response Optimization Service
  description: Optimizes chatbot reply quality based on real-time user feedback
spec:
  type: service
  lifecycle: production
  owner: user:Parv
  providesApis:
    - optimization-api
  partOf:
    - ai-optimization-system
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: knowledge-base-service
  title: Knowledge Base Service
  description: Manages dynamic FAQs, help articles, and chatbot fallback replies
spec:
  type: service
  lifecycle: production
  owner: user:Parv
  providesApis:
    - knowledge-base-api
  partOf:
    - content-management-system
