# apiVersion: backstage.io/v1alpha1
# kind: User
# metadata:
#   name: Ankit
# spec:
#   profile:
#     displayName: Ankit Bansal
#     email: ankit.b@cywarden.com
#   memberOf:
#     - "group: chatbot-team"

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: chat-processing-service
  title: Chat Processing Service
  description: Core service that routes user messages to NLP and session store
spec:
  type: service
  lifecycle: production
  owner: user:Ankit
  providesApis:
    - chat-api
  consumesApis:
    - nlp-api
    - session-api
  partOf:
    - chatbot-system
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: user-auth-service
  title: User Authentication Service
  description: Handles user sign-in, sign-up, and session validation
spec:
  type: service
  lifecycle: production
  owner: user:Ankit
  providesApis:
    - auth-api
  consumesApis:
    - db-api
  partOf:
    - auth-system
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: analytics-service
  title: Analytics Service
  description: Tracks and aggregates usage metrics and user activity
spec:
  type: service
  lifecycle: production
  owner: user:Ankit
  providesApis:
    - analytics-api
  consumesApis:
    - db-api
  partOf:
    - analytics-system
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: chatbot-system
  title: Chatbot System
  description: System comprising components responsible for chatbot interaction
spec:
  type: system
  lifecycle: production
  owner: user:Ankit
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: auth-system
  title: Authentication System
  description: System handling all aspects of authentication and access control
spec:
  type: system
  lifecycle: production
  owner: user:Ankit
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: marketing-site
  title: Marketing Website
  description: Public-facing marketing website for the product
spec:
  type: website
  lifecycle: production
  owner: user:Ankit
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: help-center-site
  title: Help Center
  description: Help center and documentation site for users
spec:
  type: website
  lifecycle: production
  owner: user:Ankit
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dashboard-frontend
  title: Dashboard Frontend
  description: Frontend website for managing and monitoring services
spec:
  type: website
  lifecycle: production
  owner: user:Ankit
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: blog-site
  title: Blog Site
  description: Official blog website showcasing updates and tutorials
spec:
  type: website
  lifecycle: production
  owner: user:Ankit
